<Project>
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ReleaseBuild)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Win_1337_Patch' and ('$(ReleaseMode)' == 'framework-dependent' or '$(ReleaseMode)' == 'self-contained')">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained Condition="'$(ReleaseMode)' == 'framework-dependent'">false</SelfContained>
    <SelfContained Condition="'$(ReleaseMode)' == 'self-contained'">true</SelfContained>
    <RuntimeFrameworkVersion>10.0.12</RuntimeFrameworkVersion>
    <TargetLatestRuntimePatch>false</TargetLatestRuntimePatch>
    <NuGetLockFilePath>$(MSBuildProjectDirectory)/packages.win-x64-$(ReleaseMode).lock.json</NuGetLockFilePath>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishAot>false</PublishAot>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
</Project>
