//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by scripts/Generate-Settings.ps1 from Settings.settings.
//     Change the source settings and rerun the generator; do not edit this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_1337_Patch.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Win_1337_Patch.SettingsGenerator", "1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get { return defaultInstance; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool @fixoffset
        {
            get { return ((bool)(this["fixoffset"])); }
            set { this["fixoffset"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool @backup
        {
            get { return ((bool)(this["backup"])); }
            set { this["backup"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool @changeOwnership
        {
            get { return ((bool)(this["changeOwnership"])); }
            set { this["changeOwnership"] = value; }
        }
    }
}
