param(
    [string] $SourcePath = (Join-Path $PSScriptRoot '../Win_1337_Patch/Properties/Settings.settings'),
    [string] $OutputPath = (Join-Path $PSScriptRoot '../Win_1337_Patch/Properties/Settings.Designer.cs'),
    [switch] $Check
)

$ErrorActionPreference = 'Stop'

Set-StrictMode -Version Latest
$SourcePath = [IO.Path]::GetFullPath($SourcePath)
$OutputPath = [IO.Path]::GetFullPath($OutputPath)
if ($SourcePath -eq $OutputPath) { throw 'Source and output paths must differ.' }

$readerSettings = [Xml.XmlReaderSettings]::new()
$readerSettings.DtdProcessing = [Xml.DtdProcessing]::Prohibit
$readerSettings.XmlResolver = $null
$reader = [Xml.XmlReader]::Create($SourcePath, $readerSettings)
try {
    $document = [Xml.XmlDocument]::new()
    $document.XmlResolver = $null
    $document.Load($reader)
}
finally { $reader.Dispose() }

$ns = [Xml.XmlNamespaceManager]::new($document.NameTable)
$ns.AddNamespace('s', 'http://schemas.microsoft.com/VisualStudio/2004/01/settings')
$root = $document.SelectSingleNode('/s:SettingsFile', $ns)
if ($null -eq $root -or
    $root.GetAttribute('GeneratedClassNamespace') -cne 'Win_1337_Patch.Properties' -or
    $root.GetAttribute('GeneratedClassName') -cne 'Settings' -or
    $root.GetAttribute('CurrentProfile') -cne '(Default)') {
    throw 'Only this project''s Settings class and default profile are supported.'
}
if ($root.SelectNodes('s:Profiles/*', $ns).Count -ne 0) {
    throw 'Custom settings profiles are not supported.'
}
$settingsNodes = $root.SelectNodes('s:Settings/s:Setting', $ns)
if ($settingsNodes.Count -eq 0) { throw 'No settings were found.' }
$names = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
$settings = foreach ($setting in $settingsNodes) {
    $name = $setting.GetAttribute('Name')
    if ($name -cnotmatch '^[A-Za-z_][A-Za-z0-9_]*$' -or -not $names.Add($name) -or $name -in @('Settings', 'Default', 'defaultInstance')) {
        throw "Invalid, reserved or duplicate setting identifier: '$name'."
    }
    if ($setting.GetAttribute('Type') -cne 'System.Boolean' -or $setting.GetAttribute('Scope') -cne 'User') {
        throw 'Only System.Boolean user-scoped settings are supported.'
    }
    $values = $setting.SelectNodes('s:Value', $ns)
    if ($values.Count -ne 1 -or $values[0].GetAttribute('Profile') -cne '(Default)' -or
        $values[0].InnerText -cnotin @('True', 'False') -or $setting.ChildNodes.Count -ne 1) {
        throw "Setting '$name' requires one default-profile Boolean value (True or False)."
    }
    [pscustomobject]@{ Name = $name; Value = $values[0].InnerText }
}

$lines = [Collections.Generic.List[string]]::new()
$lines.AddRange([string[]]@(
    '//------------------------------------------------------------------------------',
    '// <auto-generated>',
    '//     Generated by scripts/Generate-Settings.ps1 from Settings.settings.',
    '//     Change the source settings and rerun the generator; do not edit this file.',
    '// </auto-generated>',
    '//------------------------------------------------------------------------------',
    '',
    'namespace Win_1337_Patch.Properties',
    '{',
    '    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]',
    '    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Win_1337_Patch.SettingsGenerator", "1.0.0")]',
    '    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase',
    '    {',
    '        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));',
    '',
    '        public static Settings Default',
    '        {',
    '            get { return defaultInstance; }',
    '        }'
))
foreach ($setting in $settings) {
    $name = $setting.Name
    $value = $setting.Value
    $lines.AddRange([string[]]@(
        '',
        '        [global::System.Configuration.UserScopedSettingAttribute()]',
        '        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]',
        "        [global::System.Configuration.DefaultSettingValueAttribute(`"$value`")]",
        "        public bool @$name",
        '        {',
        "            get { return ((bool)(this[`"$name`"])); }",
        "            set { this[`"$name`"] = value; }",
        '        }'
    ))
}
$lines.AddRange([string[]]@('    }', '}'))
# Stable LF/UTF-8 output; no timestamps, machine paths or runtime versions.
$generated = ($lines -join "`n") + "`n"
$existing = if ([IO.File]::Exists($OutputPath)) { [IO.File]::ReadAllText($OutputPath) } else { $null }
# Accept checkout line-ending conversion while preserving untouched output.
$current = $null -ne $existing -and ($existing.Replace("`r`n", "`n") -ceq $generated)
if ($Check) {
    if ($null -eq $existing) { throw 'Generated settings output is missing.' }
    if (-not $current) { throw 'Generated settings output is stale. Run scripts/Generate-Settings.ps1.' }
    Write-Host 'Generated settings output is current.'
}
elseif ($current) {
    Write-Host 'Generated settings output is unchanged.'
}
else {
    [IO.File]::WriteAllText($OutputPath, $generated, [Text.UTF8Encoding]::new($false))
    Write-Host 'Generated settings output updated.'
}
